import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Nav from "@/components/Nav";
=======
import { Toaster } from "sonner";
>>>>>>> 3dda69b999cfc1f2e92de2b41af1bc219a2990d9

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        <div className="w-full max-w-5xl mx-auto">
          <Nav />
          <div className="pt-10">{children}</div>
        </div>
=======
        <Toaster richColors position="top-right" />
        {children}
>>>>>>> 3dda69b999cfc1f2e92de2b41af1bc219a2990d9
      </body>
    </html>
  );
}
